# Generated by Django 4.0 on 2022-01-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollInfo',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('nbr_voices', models.PositiveIntegerField(null=True)),
                ('logins_cands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins_cands', to='login.userinfo')),
                ('logins_voters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins_voters', to='login.userinfo')),
            ],
        ),
    ]
