# Generated by Django 4.0 on 2021-12-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollinfo',
            old_name='login_cands',
            new_name='logins_cands',
        ),
        migrations.RenameField(
            model_name='pollinfo',
            old_name='login_voters',
            new_name='logins_voters',
        ),
    ]
