# Generated by Django 4.0 on 2022-01-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollAndUserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(verbose_name='IsVoter')),
            ],
        ),
        migrations.AddField(
            model_name='pollinfo',
            name='users',
            field=models.ManyToManyField(through='poll.PollAndUserRelationship', to='login.UserInfo'),
        ),
        migrations.AlterField(
            model_name='pollinfo',
            name='logins_cands',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pollinfo',
            name='logins_voters',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pollinfo',
            name='nbr_voices',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='pollanduserrelationship',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollinfo'),
        ),
        migrations.AddField(
            model_name='pollanduserrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userinfo'),
        ),
    ]
