# Generated by Django 4.0 on 2022-01-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('login_id', models.TextField()),
                ('is_staff', models.BooleanField()),
                ('group', models.TextField()),
                ('anonymize_date', models.DateTimeField()),
            ],
        ),
    ]
