# Generated by Django 4.0 on 2022-01-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_id_userinfo_intra_id_alter_userinfo_info_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='info_data',
        ),
    ]
