# Generated by Django 4.0 on 2022-01-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_userinfo_info_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='login_id',
            field=models.CharField(max_length=16),
        ),
    ]
